### PR TITLE
chore: Trigger PR

### PR DESCRIPTION
**Pull request by NelsonBN**
## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] Implemented tests for new features.
- [x] I tested the features already implemented.
- [x] Added usage examples in the readme.

### CODE REVIEW

**Review by NelsonBN — COMMENTED** [review]
All OK

**Review by NelsonBN — COMMENTED** [review]
All OK

**Review by NelsonBN — COMMENTED** [review]
All OK

**Review by NelsonBN — COMMENTED** [review]
All OK

**Review by NelsonBN — COMMENTED** [review]
All OK

**Review by filipe11402 — APPROVED** [review]
All OK

**Comment by filipe11402** [comment]
A good feature to add, would be in `FinancialValidation` to have a method like `FinancialValidation.ExpirationDateShouldBeValid()` , and inside it, have the check if the month is > than NOW and the same for the year.

**Review by NelsonBN — COMMENTED** [review]
All OK

**Comment by NelsonBN** [comment]
@filipe11402 the new method to validate expiry card date
https://github.com/TechNobre/PowerUtils.Results.Validations/blob/feat/kickoff/src/FinancialValidations.cs#L165

**Review by filipe11402 — APPROVED** [review]
@NelsonBN i really loved the way you achieved the end result...
All OK!

**Review by NelsonBN — COMMENTED** [review]
All OK

**Review by filipe11402 — APPROVED** [review]
All OK

**Pull request merged**
